# Generated by Django 3.1.5 on 2021-01-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='default_destination',
            new_name='is_default',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email_agree',
            new_name='is_email_agreed',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='sms_agree',
            new_name='is_sms_agreed',
        ),
        migrations.AlterField(
            model_name='destination',
            name='detail_address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='destination',
            name='street_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
    ]
