# Generated by Django 3.1.5 on 2021-01-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productoption_name'),
        ('users', '0003_auto_20210115_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_product_likes',
            field=models.ManyToManyField(related_name='user_product_likes', through='users.UserProductLike', to='products.Product'),
        ),
    ]
