# Generated by Django 3.1.5 on 2021-01-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=45),
        ),
    ]
