# Generated by Django 3.1.5 on 2021-01-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210114_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoption',
            name='name',
            field=models.CharField(default='asdf', max_length=45),
            preserve_default=False,
        ),
    ]
