# Generated by Django 3.1.5 on 2021-01-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productoption_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_keyword',
            field=models.ManyToManyField(related_name='product_keyword', through='products.ProductKeyword', to='products.Keyword'),
        ),
    ]
